WITH CTE AS (
  SELECT *,
    COUNT(*) OVER (ORDER BY ID RANGE BETWEEN CURRENT ROW AND 2 FOLLOWING) AS F_C,
    COUNT(*) OVER (ORDER BY ID RANGE BETWEEN  2 PRECEDING  and CURRENT ROW ) AS P_C,
    COUNT(*) OVER (ORDER BY ID RANGE BETWEEN  1 PRECEDING AND 1 FOLLOWING) AS C_C
  FROM Stadium
  WHERE people > 99
)
SELECT id, visit_date, people FROM CTE C
WHERE C.F_C = 3 OR C.C_C = 3 OR C.P_C = 3
ORDER BY C.visit_date;

